name: tests

on: [push]

jobs:
  pep8:
    runs-on: ubuntu-latest
    container:
      image: themattrix/tox
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Tests
      run: |
          tox -v
